### ISSUE TITLE
Stale repo?

### ISSUE THREAD

**Issue by bitsandsalsa** [dell/ansible-powerscale#1]
Is this repo now stale in favor of the [Dell Storage unified repo](https://github.com/dell/ansible-storage-automation)?

**Comment by anil-degwekar** [comment]
Hi,

This repo will hold the Ansible modules for PowerScale (previous name Isilon). The 'Dell Storage unified repo' contains sample Ansible playbooks for all of Dell storage -- so it is a complimentary repo.

You may use the 'ansible-isilon' repo for now if you want the Ansible modules for PowerScale.
