### ISSUE TITLE
[BUG]: Module networkpool fails with ValueError: Invalid value for `firewall_policy`, must not be `None`

### ISSUE THREAD

**Issue by nikolisg7** [dell/ansible-powerscale#103]
**Describe the bug**
Running the module `dellemc.powerscale.networkpool` fails with ValueError: Invalid value for `firewall_policy`, must not be `None` (stack trace below)

**To Reproduce**
Run the module from collection dellemc.powerscale 3.2.0 against OneFS 9.7.1.0 to create/modify a network pool

**Expected behavior**
Creation / Modification of the network pool

**Screenshots**

**Logs**
The full traceback is:
Traceback (most recent call last):
  File /Users/dduck/.ansible/tmp/ansible-tmp-1722606685.338311-23455-234749811521570/AnsiballZ_networkpool.py, line 107, in <module>
    _ansiballz_main()
  File /Users/dduck/.ansible/tmp/ansible-tmp-1722606685.338311-23455-234749811521570/AnsiballZ_networkpool.py, line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File /Users/dduck/.ansible/tmp/ansible-tmp-1722606685.338311-23455-234749811521570/AnsiballZ_networkpool.py, line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.dellemc.powerscale.plugins.modules.networkpool', init_globals=dict(_module_fqn='ansible_collections.dellemc.powerscale.plugins.modules.networkpool', _modlib_path=modlib_path),
  File /Users/dduck/anaconda3/envs/ansible/lib/python3.10/runpy.py, line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File /Users/dduck/anaconda3/envs/ansible/lib/python3.10/runpy.py, line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File /Users/dduck/anaconda3/envs/ansible/lib/python3.10/runpy.py, line 86, in _run_code
    exec(code, run_globals)
  File /var/folders/ch/5vd8v1jn0798dcmzkvygb4qw0000gn/T/ansible_dellemc.powerscale.networkpool_payload_3p0kl2oh/ansible_dellemc.powerscale.networkpool_payload.zip/ansible_collections/dellemc/powerscale/plugins/modules/networkpool.py, line 1019, in <module>
  File /var/folders/ch/5vd8v1jn0798dcmzkvygb4qw0000gn/T/ansible_dellemc.powerscale.networkpool_payload_3p0kl2oh/ansible_dellemc.powerscale.networkpool_payload.zip/ansible_collections/dellemc/powerscale/plugins/modules/networkpool.py, line 1015, in main
  File /var/folders/ch/5vd8v1jn0798dcmzkvygb4qw0000gn/T/ansible_dellemc.powerscale.networkpool_payload_3p0kl2oh/ansible_dellemc.powerscale.networkpool_payload.zip/ansible_collections/dellemc/powerscale/plugins/modules/networkpool.py, line 990, in handle
  File /var/folders/ch/5vd8v1jn0798dcmzkvygb4qw0000gn/T/ansible_dellemc.powerscale.networkpool_payload_3p0kl2oh/ansible_dellemc.powerscale.networkpool_payload.zip/ansible_collections/dellemc/powerscale/plugins/modules/networkpool.py, line 498, in get_network_pool
  File /Users/dduck/anaconda3/envs/ansible/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api/network_groupnets_api.py, line 616, in get_subnets_subnet_pool
    (data) = self.get_subnets_subnet_pool_with_http_info(subnets_subnet_pool_id, groupnet, subnet, **kwargs)  # noqa: E501
  File /Users/dduck/anaconda3/envs/ansible/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api/network_groupnets_api.py, line 694, in get_subnets_subnet_pool_with_http_info
    return self.api_client.call_api(
  File /Users/dduck/anaconda3/envs/ansible/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api_client.py, line 341, in call_api
    return self.__call_api(resource_path, method,
  File /Users/dduck/anaconda3/envs/ansible/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api_client.py, line 185, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File /Users/dduck/anaconda3/envs/ansible/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api_client.py, line 257, in deserialize
    return self.__deserialize(data, response_type)
  File /Users/dduck/anaconda3/envs/ansible/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api_client.py, line 296, in __deserialize
    return self.__deserialize_model(data, klass)
  File /Users/dduck/anaconda3/envs/ansible/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api_client.py, line 671, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File /Users/dduck/anaconda3/envs/ansible/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api_client.py, line 273, in __deserialize
    return [self.__deserialize(sub_data, sub_kls)
  File /Users/dduck/anaconda3/envs/ansible/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api_client.py, line 273, in <listcomp>
    return [self.__deserialize(sub_data, sub_kls)
  File /Users/dduck/anaconda3/envs/ansible/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api_client.py, line 296, in __deserialize
    return self.__deserialize_model(data, klass)
  File /Users/dduck/anaconda3/envs/ansible/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api_client.py, line 673, in __deserialize_model
    instance = klass(**kwargs)
  File /Users/dduck/anaconda3/envs/ansible/lib/python3.10/site-packages/isilon_sdk/v9_5_0/models/subnets_subnet_pools_pool.py, line 128, in __init__
    self.firewall_policy = firewall_policy
  File /Users/dduck/anaconda3/envs/ansible/lib/python3.10/site-packages/isilon_sdk/v9_5_0/models/subnets_subnet_pools_pool.py, line 321, in firewall_policy
    raise ValueError(Invalid value for , must not be )  # noqa: E501

**System Information (please complete the following information):**
 - OS/Version: [e.g. RHEL 7.6] OneFS 9.7.1.0
 - Ansible Version [e.g. 2.12] 2.16
 - Python Version [e.g. 3.9]  3.10.11
 - isilon-sdk 0.3.0.1
 - Ansible powerscale collection: 3.2.0

**Additional context**

**Comment by trisha-dell** [comment]
Hello @nikolisg7,

Thank you for reaching out. We are investigating this issue. Meanwhile, you can use the following sample playbooks for your operations.
`---
- name: Network pool Operations on PowerScale
  hosts: localhost
  connection: local
  vars:
    host: "10.225.108.2"
    port: 8080
    username: "admin"
    password: "Password123!"
    Groupnet: "Sample_nwpool_groupnet"
    Subnet: "Sample_nwpool_subnet"
    pool_name: "Sample_pool_1"
    high_range: "10.**.**.13"
    low_range: "10.**.**.10"
    sr_gateway: "10.**.**.2"
    sr_prefixlen: 21
    sr_subnet: "10.**.**..0"
    high_range_new: "10.**.**.15"
    low_range_new: "10.**.**.11"
    sr_gateway_new: "10.**.**..1"
    sr_prefixlen_new: 32
    sr_subnet_new: "10.**.**.0"
    access_zone: "Sample_access_zone"
    sc_dns_zone: "10.**.**.169"
    description: "Sample description"
    iface_1: "iface_1"
    iface_2: "iface_2"
    sc_dns_zone_aliases: "Sample_dns_zone"
  tasks:
  - name: Create network pool
    ansible.builtin.uri:
      url: "https://{{host}}:{{port}}/platform/16/network/groupnets/{{Groupnet}}/subnets/{{Subnet}}/pools"
      method: POST
      user: "{{ username }}"
      password: "{{ password }}"
      force_basic_auth: true
      status_code: 201
      return_content: true
      validate_certs: false
      headers:
        Content-Type: "application/json"
      body_format: json
      body:
        name: "{{ pool_name }}"
        ranges:
        - high: "{{ high_range }}"
          low: "{{ low_range }}"
        static_routes:
        - gateway: "{{ sr_gateway }}"
          prefixlen: "{{ sr_prefixlen }}"
          subnet: "{{ sr_subnet }}"
        access_zone: "{{ access_zone }}"
    register: assign_roles
    run_once: true

  - name: Get network pool details
    ansible.builtin.uri:
      url: "https://{{host}}:{{port}}/platform/16/network/groupnets/{{Groupnet}}/subnets/{{Subnet}}/pools/{{pool_name}}"
      method: GET
      user: "{{ username }}"
      password: "{{ password }}"
      force_basic_auth: true
      status_code: 200
      return_content: true
      validate_certs: false
      headers:
        Content-Type: "application/json"
    register: assign_roles
    run_once: true

  - name: Modify network pool details
    ansible.builtin.uri:
      url: "https://{{host}}:{{port}}/platform/16/network/groupnets/{{Groupnet}}/subnets/{{Subnet}}/pools/{{pool_name}}"
      method: PUT
      user: "{{ username }}"
      password: "{{ password }}"
      force_basic_auth: true
      status_code: 204
      return_content: true
      validate_certs: false
      headers:
        Content-Type: "application/json"
      body_format: json
      body:
        name: "{{ pool_name }}"
        ranges:
        - high: "{{ high_range_new }}"
          low: "{{ low_range_new }}"
        static_routes:
        - gateway: "{{ sr_gateway_new }}"
          prefixlen: "{{ sr_prefixlen_new }}"
          subnet: "{{ sr_subnet_new }}"
        description: "{{ description }}"
        access_zone: "{{ access_zone }}"
        sc_dns_zone: "{{ sc_dns_zone }}"
        sc_connect_policy: "round_robin"
        sc_failover_policy: "round_robin"
        rebalance_policy: "auto"
        alloc_method: "static"
        sc_auto_unsuspend_delay: 0
        sc_ttl: 0
        aggregation_mode: "roundrobin"
        sc_dns_zone_aliases:
        - "{{ sc_dns_zone_aliases }}"
        ifaces:
        - iface: "{{ iface_1 }}"
          lnn: 1
        - iface: "{{ iface_2 }}"
          lnn: 1
    register: modify_nwpool
    run_once: true

  - name: Delete network pool
    ansible.builtin.uri:
      url: "https://{{host}}:{{port}}/platform/16/network/groupnets/{{Groupnet}}/subnets/{{Subnet}}/pools/{{pool_name}}"
      method: DELETE
      user: "{{ username }}"
      password: "{{ password }}"
      force_basic_auth: true
      status_code: 204
      return_content: true
      validate_certs: false
      headers:
        Content-Type: "application/json"
    register: delete_nwpool
    run_once: true
`

Feel free to reach out in case of any other queries.
