### ISSUE TITLE
Create Network pool documentation is wrong

### ISSUE THREAD

**Issue by dileepbg** [dell/ansible-powerscale#12]
@rajendravarma077 @meshuga @anupamaloke @walker2 @dattaarindam 

From Documentation, below is the code to create a network pool. But getting below error stating unsupported parameters name

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (dellemc.powerscale.dellemc_powerscale_subnet) module: access_zone, pool Supported parameters include: api_password, api_user, description, gateway_priority, groupnet_name, netmask, new_subnet_name, onefs_host, port_no, state, subnet_name, subnet_params, verify_ssl"}

Do we need to use dellemc_powerscale_subnet or dellemc_powerscale_networkpool.

- name: Create Network Pool
      dellemc_powerscale_subnet:
      onefs_host: "{{onefs_host}}"
      api_user: "{{api_user}}"
      api_password: "{{api_password}}"
      verify_ssl: "{{verify_ssl}}"
      groupnet: "groupnet0"
      subnet: "subnet0"
      pool: "Test_Pool_2"
      access_zone: "system"
      state: "present"

**Comment by rajendraindukuri** [comment]
Hi @dileepbg Thanks for pointing that out. Its a documentation miss. We should use 'dellemc_powerscale_networkpool'
We will correct it.

Thanks
Rajendra

**Comment by anupamaloke** [comment]
Closed by #25
