### ISSUE TITLE
[BUG]: ansible-builder introspect fails with file not found

### ISSUE THREAD

**Issue by murrahjm** [dell/ansible-powerscale#32]
**Describe the bug**
When attempting to install this collection into an execution environment via the ansible-builder command, the build fails with an error that the requirements.txt file is not found.  This appears to be caused by the use of a relative path in the meta/execution-environment.yml file.

**To Reproduce**
1. Step 1 install the collection with `ansible-galaxy collection install dellemc.powerscale`
2. Step 2 test collection with ` ansible-builder introspect --sanitize ~/.ansible/collections/`
3. Step 3 see error 
Expected requirements file not present at: /home/user/.ansible/collections/ansible_collections/dellemc/requirements.txt
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.ansible/collections/ansible_collections/dellemc/powerscale/../requirements.txt'
Note the parent folder reference `../requirements.txt`
4. Step 4 edit meta/execution-environment.yml and remove the relative path
```yaml
---
version: 1
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
```
6. Step 5 test collection again and see proper output

**Expected behavior**
ansible-builder introspect command should list correct dependencies

```yaml
---
python:
- 'certifi  # from collection dellemc.powerscale'
- 'isi-sdk-9-1-0  # from collection dellemc.powerscale'
- 'isi-sdk-8-1-1  # from collection dellemc.powerscale'
- 'setuptools  # from collection dellemc.powerscale'
- 'six  # from collection dellemc.powerscale'
```

**System Information (please complete the following information):**
ansible --version
ansible [core 2.12.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.8 (default, Aug 25 2021, 16:13:02) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True

**Comment by anupamaloke** [comment]
@murrahjm, This issue has also been reported here: https://github.com/ansible/ansible-builder/issues/399 and a solution for resolving this as well:

> @jompins After debugging a bit, I found that `dellemc.powerscale` collection added `meta/execution-environment.yml` file with [1.6.0 release](https://github.com/dell/ansible-powerscale/commit/72b1b848cc59caa04c2cde3392d50ab087aec7ba). But Python dependency `dependencies` mentioned in [execution-environment.yml](https://github.com/dell/ansible-powerscale/blob/0ee86eaac41f26ddd057ac2c688e4f85dc78432f/meta/execution-environment.yml#L5) should be
> 
> ```yaml
> ...
> dependencies:
>   galaxy: requirements.yml
>   python: requirements.txt
> ...
> ```
> 
> instead of
> 
> ```yaml
> ...
> dependencies:
>   galaxy: ../requirements.yml
>   python: ../requirements.txt
> ...
> ```

We will fix this asap. Meanwhile, you can edit the execution_environment.yml file to make the above changes to get it working.
