### ISSUE TITLE
[BUG]: meta/runtime.yml contains redirects that will stop working with ansible-core 2.14

### ISSUE THREAD

**Issue by felixfontein** [dell/ansible-powerscale#34]
**Describe the bug**
The `redirect` entries in `meta/runtime.yml` do not contain FQCNs, but short names: https://github.com/dell/ansible-powerscale/blob/1.6.0/meta/runtime.yml#L6-L121

This will result in an error with ansible-core 2.14, see https://github.com/ansible/ansible/pull/78755.

**Comment by Jennifer-John** [comment]
Closing this issue as it is fixed as part of PR #45
