### ISSUE TITLE
[BUG]: PowerScale Ansible v1.6 - if default root/a credentials used any output containing "a" will become "*********"

### ISSUE THREAD

**Issue by JshMyr** [dell/ansible-powerscale#37]
**Describe the bug**

PowerScale Ansible Module v1.6 dellemc.powerscale.smb returns ******** for character "a"?   shows status "changed" instead of the expected "ok", and the output also contains some "a" characters replaced with eight asterisk* characters in its place.   This only occurs if the password for authentication to run the module parameters is also "a".  It could be this is an as-designed feature to protect the password if the hash matches, but, it should not result in **status: changed** in any way, this is designed to protect a password if it is inadvertently typed into the ansible parameters

**To Reproduce**

1. PowerScale Ansible Module 1.6, Isilon OneFS version 9.2 and higher
2. Run the following ansible queries / parameters (as an example - not limited to this set of parameters only)

name: Get SMB share permissions from the cluster
dellemc.powerscale.smb:
onefs_host: "{{onefs_host}}"
verify_ssl: "{{verify_ssl}}"
api_user: "{{api_user}}"
api_password: "{{api_password}}"
access_zone: "{{item.zone}}"
share_name: "{{item.share}}"
state: present
register: getpermissions_result
with_items: "{{share_list}}"

3. Observe the error behavior in the output, which is seen regardless of the no_log being set set to false or true.

**Unexpected behavior**

changed: [fbkppexfer] => (item={'share': 'PKITA_24891470_ADT', 'zone': 'PPEXFER-Ring0'}) => { "ansible_loop_var": "item", "changed": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",.... ", "create_permissions": "def********ult ********cl",

**Expected behavior**
Expected behavior example...

ok: [DBISILONSIMULATOR] => (item={'share': 'CreatedFromAnsible', 'zone': 'testzone'}) => { "ansible_loop_var": "item", "changed": false, "invocation": { "module_args": { "access_based_enumeration": null, "access_based_enumeration_root_only": null, "access_zone": "testzone", "api_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",...... "create_permissions": "default acl",

**Screenshots**
NA

**Logs**
NA

**System Information (please complete the following information):**
 - OS/Version: REL 8.4
 - Ansible Version PowerScale Module v1.6.0
 - Python Version 3.9
 - Additional Information  Isilon OneFS 9.2.1.12

**Additional context**
https://www.dell.com/community/Automation/PowerScale-Ansible-Module-v1-6-dellemc-powerscale-smb-returns/m-p/8269586/thread-id/364#M366

Changing the password from "a" to something less common  that is not included in the clear-text output received back from the parameters sent proves to be a workaround to the issue.  Still - this shouldn't ever happen.  Thanks.

**Comment by kuttattz** [comment]
Hi @JshMyr 
Any string marked no-log, including passwords, are replaced with ****. This is merely to protect your sensitive data. Ansible replaces every single string that matches the password string with an asterisk.
Please find the below github issues raised to ansible for similar cases:

- https://github.com/ansible/ansible/issues/68400
- https://github.com/ansible/ansible/issues/76872

Thanks

**Comment by anupamaloke** [comment]
Closing this issue as it is the current ansible behavior and not related to PowerScale ansible modules.
