### ISSUE TITLE
[FEATURE]: FS creation with a custom user

### ISSUE THREAD

**Issue by Bonifucksy** [dell/ansible-powerscale#39]
**Describe the solution you'd like**
It should be possible to create a File System / directory with a custom user instead of root. Using root account in automation software is a high security risk.

Known issue number 2: https://github.com/dell/ansible-powerscale/blob/master/docs/Release%20Notes.md#known-issues

**Comment by anupamaloke** [comment]
@Bonifucksy, as you have rightly mentioned, this is a known issue in previous release. We need to check with the OneFS team on when this is going to be fixed.

**Comment by Jennifer-John** [comment]
Hi @Bonifucksy,

On discussion with OneFS team, granting ISI_PRIV_IFS_RESTORE privileges through a role to the custom user should enable the creation of filesystem with acl permissions. This seems to work for me. Could you please check the same?

Thanks,
Jennifer.

**Comment by Bonifucksy** [comment]
Hey @Jennifer-John 

I just tried that in my lab, unfortunately the playbook failed.
```
DBISILONSIMULATOR-1# isi auth roles privileges list ansible_role
ID
----------------------
ISI_PRIV_LOGIN_PAPI
ISI_PRIV_AUTH
ISI_PRIV_SMB
ISI_PRIV_IFS_RESTORE
ISI_PRIV_NS_IFS_ACCESS
----------------------
Total: 5



The full traceback is:
  File "/tmp/ansible_dellemc.powerscale.filesystem_payload__qzg_dv6/ansible_dellemc.powerscale.filesystem_payload.zip/ansible_collections/dellemc/powerscale/plugins/modules/filesystem.py", line 618, in get_filesystem
  File "/home/broot/ansible/lib/python3.9/site-packages/isi_sdk_9_1_0/api/namespace_api.py", line 1543, in get_directory_metadata
    (data) = self.get_directory_metadata_with_http_info(directory_metadata_path, metadata, **kwargs)  # noqa: E501
  File "/home/broot/ansible/lib/python3.9/site-packages/isi_sdk_9_1_0/api/namespace_api.py", line 1614, in get_directory_metadata_with_http_info
    return self.api_client.call_api(
  File "/home/broot/ansible/lib/python3.9/site-packages/isi_sdk_9_1_0/api_client.py", line 341, in call_api
    return self.__call_api(resource_path, method,
  File "/home/broot/ansible/lib/python3.9/site-packages/isi_sdk_9_1_0/api_client.py", line 173, in __call_api
    response_data = self.request(
  File "/home/broot/ansible/lib/python3.9/site-packages/isi_sdk_9_1_0/api_client.py", line 363, in request
    return self.rest_client.GET(url,
  File "/home/broot/ansible/lib/python3.9/site-packages/isi_sdk_9_1_0/rest.py", line 318, in GET
    return self.request("GET", url,
  File "/home/broot/ansible/lib/python3.9/site-packages/isi_sdk_9_1_0/rest.py", line 236, in request
    raise ApiException(http_resp=r)
failed: [DBISILONSIMULATOR] (item={'share': 'test_restore_perm2', 'zone': 'zoneinsidezoneinsidezone', 'zone_id': 4, 'oplocks': True, 'description': 'SMB rules!', 'path': '/test_restore_perm2', 'smb_permissions': [{'user_name': 'user_uid_5k', 'permission': 'read', 'permission_type': 'allow', 'provider_type': 'local'}], 'owner': 'root', 'acl_permissions': [{'user_name': 'user_uid_5k', 'accessrights': ['dir_gen_read', 'dir_gen_write', 'std_delete'], 'accesstype': 'allow', 'inherit_flags': [], 'trustee': {'name': 'user_uid_5k', 'provider_type': 'local'}}]}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "access_control": null,
            "access_control_rights": null,
            "access_control_rights_state": null,
            "access_zone": "zoneinsidezoneinsidezone",
            "api_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "api_user": "ansible_user",
            "group": null,
            "list_snapshots": false,
            "onefs_host": "192.168.40.3",
            "owner": {
                "name": "root",
                "provider_type": "file"
            },
            "path": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port_no": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "quota": null,
            "recursive": true,
            "recursive_force_delete": false,
            "state": "present",
            "verify_ssl": false
        }
    },
    "item": {
        "acl_permissions": [
            {
                "accessrights": [
                    "dir_gen_read",
                    "dir_gen_write",
                    "std_delete"
                ],
                "accesstype": "allow",
                "inherit_flags": [],
                "trustee": {
                    "name": "user_uid_5k",
                    "provider_type": "local"
                },
                "user_name": "user_uid_5k"
            }
        ],
        "description": "SMB rules!",
        "oplocks": true,
        "owner": "root",
        "path": "/test_restore_perm2",
        "share": "test_restore_perm2",
        "smb_permissions": [
            {
                "permission": "read",
                "permission_type": "allow",
                "provider_type": "local",
                "user_name": "user_uid_5k"
            }
        ],
        "zone": "zoneinsidezoneinsidezone",
        "zone_id": 4
    },
    "msg": "Failed to get details of Filesystem ifs/testzone/zoneinsidezone/zoneinsidezoneinsidezone******** with error  { errors : [ { code : AEC_FORBIDDEN , message : Access denied. open object 'testzone/zoneinsidezone/zoneinsidezoneinsidezone********' in store 'ifs' } ] }  "
}
```

**Comment by Bonifucksy** [comment]
Hey @Jennifer-John,

I just checked that, the module creates a directory, but returns 'failed' status with error: `msg": "Failed to get details of Filesystem ifs/testzone/zoneinsidezone/zoneinsidezoneinsidezone******** with error  { errors : [ { code : AEC_FORBIDDEN , message : Access denied. open object 'testzone/zoneinsidezone/zoneinsidezoneinsidezone********' in store 'ifs'`
`failed: [DBISILONSIMULATOR] (item={'share': 'test_restore_perm3', 'zone': 'zoneinsidezoneinsidezone', 'zone_id': 4, 'oplocks': True, 'description': 'SMB rules!', 'path': '/test_restore_perm3', 'smb_permissions': [{'user_name': 'user_uid_5k', 'permission': 'read', 'permission_type': 'allow', 'provider_type': 'local'}], 'owner': 'root', 'acl_permissions': [{'user_name': 'user_uid_5k', 'accessrights': ['dir_gen_read', 'dir_gen_write', 'std_delete'], 'accesstype': 'allow', 'inherit_flags': [], 'trustee': {'name': 'user_uid_5k', 'provider_type': 'local'}}]}) => {"ansible_loop_var": "item", "changed": false, "item": {"acl_permissions": [{"accessrights": ["dir_gen_read", "dir_gen_write", "std_delete"], "accesstype": "allow", "inherit_flags": [], "trustee": {"name": "user_uid_5k", "provider_type": "local"}, "user_name": "user_uid_5k"}], "description": "SMB rules!", "oplocks": true, "owner": "root", "path": "/test_restore_perm3", "share": "test_restore_perm3", "smb_permissions": [{"permission": "read", "permission_type": "allow", "provider_type": "local", "user_name": "user_uid_5k"}], "zone": "zoneinsidezoneinsidezone", "zone_id": 4}, "msg": "Failed to get details of Filesystem ifs/testzone/zoneinsidezone/zoneinsidezoneinsidezone******** with error  { errors : [ { code : AEC_FORBIDDEN , message : Access denied. open object 'testzone/zoneinsidezone/zoneinsidezoneinsidezone********' in store 'ifs' } ] }  "}`
```
DBISILONSIMULATOR-1# ls -led /ifs/testzone/zoneinsidezone/zoneinsidezoneinsidezone/test_restore_perm3
drwx------     2 root  2000  0 Sep 30 13:36 /ifs/testzone/zoneinsidezone/zoneinsidezoneinsidezone/test_restore_perm3
 OWNER: user:root
 GROUP: group:2000
 SYNTHETIC ACL
 0: user:root allow dir_gen_read,dir_gen_write,dir_gen_execute,std_write_dac,delete_child
 1: group:2000 allow std_read_dac,std_synchronize,dir_read_attr
```

**Comment by Jennifer-John** [comment]
Hi @Bonifucksy 

Could you add the privilege ISI_PRIV_NS_TRAVERSE  for the Namespace Traverse access to the role and try?

Thanks,
Jennifer.
