### ISSUE TITLE
[BUG]: smartquota and smb modules use the `path` keyword inconsitently

### ISSUE THREAD

**Issue by mophahr** [dell/ansible-powerscale#41]
**Describe the bug**
When creating a share with ("directory"-type) smartquota in an access_zone, the `path` value needs to start with `/` in the smartquota module. Without it, it fails.

**To Reproduce**
1. create a smb share using `dellemc.powerscale.smb` with `path: "example"`
2. create a smartquota on that share using `dellemc.powerscale.smartquota`  with `quota_type: "directory"` and `path: "example"`.

This results in an error `code: AEC_NOT_FOUND, message: Path not found ...`
Replacing `path: "example"` with `path: "/example"` in step 2 creates no error.

**Expected behavior**
`path` should behave consistently.

**Screenshots**

**Logs**
If applicable, submit logs or stack traces from the affected services

**System Information (please complete the following information):**
 - dellemc.powerscale 1.7.0
 - Ansible 2.13.4
 - Python 3.9.13

**Comment by anupamaloke** [comment]
@mophahr , thank you for submitting this issue. We have added it to the backlog and will triage it accordingly.

**Comment by anupamaloke** [comment]
Fixed by #51
