### ISSUE TITLE
[FEATURE]: Find & close smb openfiles

### ISSUE THREAD

**Issue by eschek87** [dell/ansible-powerscale#43]
**Describe the solution you'd like**
We would like to have a module that find & close smb openfiles. There is a cli command for that "isi_for_array -s isi smb openfiles list" and also a restapi endpoint "/platform/1/protocols/smb/openfiles". So this should be possible...

**Comment by anupamaloke** [comment]
Closing as this has been added as part of the 1.9.0 release (#51)

**Comment by wf1-brandon-grant** [comment]
Hi there,
I am trying to migrate a self written Ansible playbook that I have to close a locked file for users, to using the `smb_file` module referenced in this PR.

This is what I was doing:
```
- name: Find where the file is open
      ansible.builtin.shell: |
        isi_for_array "isi smb openfiles list" | grep -i "{{ file_path }}"
      register: open_files

    - name: Iterate over open files and close them
      ansible.builtin.command: |
        isi_for_array --nodes {{ item.split(':')[0].split('-')[2] | int }} "isi smb openfiles close --id={{ item.split(':')[1] | regex_replace('[^0-9]+', '') }} --force"
      with_items: "{{ open_files.stdout_lines }}"
```

Issue I am seeing is that when running `dellemc.powerscale.smb_file` using the FQDN of our loadbalancer, this obviously connects to a random node in the cluster and executes the module. The result coming back is then different each time. As it only lists or closes the files open on that node.

Is there anyway to make the module act as though it is running the `isi_for_array` command and search files across the cluster. Or would I need to implement an inventory for each node in the cluster and loop over them? (If so I am likely to stick with the ssh commands)

Apologies if this shows a poor understanding of Isilon technology, I am not a storage engineer.

**Comment by anupamaloke** [comment]
@wf1-brandon-grant, thank you for submitting this use-case. I will check with the team and get back on this quickly.

**Comment by wf1-brandon-grant** [comment]
Hi @anupamaloke -
Should I submit an issue for this? Or has there been movement in the background?
