### ISSUE TITLE
[FEATURE]: Need Ansible collection support to manage User Mapping settings

### ISSUE THREAD

**Issue by sigbjornaib** [dell/ansible-powerscale#47]
**Describe the solution you'd like**
I would like to be able to manage User Mapping using Ansible

**Describe alternatives you've considered**
None

**Additional context**
We use many access zones, and we use Ansible Automation Platform to manage our Isilon/PowerScale clusters. It would be very beneficial to manage the User Mapping rules in Ansible Code as well.

**Comment by anupamaloke** [comment]
@sigbjornaib, thank you for submitting this feature request. This has been added to the backlog .

**Comment by anupamaloke** [comment]
Closed by #56
