### ISSUE TITLE
Quotas use int type instead of float

### ISSUE THREAD

**Issue by aerenr** [dell/ansible-powerscale#5]
https://github.com/dell/ansible-powerscale/blob/1df42fb01e9ca1cfbf80b09a0a03c07bd80a13ff/plugins/modules/dellemc_powerscale_smartquota.py

Line: 808-810 are setting the limit_size using ints. Can we use floats instead so that we can easily implement a hard limit of 1.5 TB, for example? 

                                advisory_limit_size=dict(type='int'),
                                soft_limit_size=dict(type='int'),
                                hard_limit_size=dict(type='int'),

**Comment by anupamaloke** [comment]
@aerenr, we are looking into this one. Meanwhile, one suggested workaround for this issue would be to set the ```*_limit_size``` argument to ```1536``` and  ```cap_unit``` to ```GB```.

**Comment by anupamaloke** [comment]
Closing the issue as it has been fixed in v1.5.0
