### ISSUE TITLE
[FEATURE]: Manage Server Certificates and CAs

### ISSUE THREAD

**Issue by xschlef** [dell/ansible-powerscale#50]
Hi,

it would be really nice if we could manage the certificates of the webserver and the certification authorities with the module. With certificate lifetime changes on the horizon, this would help all users that have to change the webserver cert every 90 days.

Basically:
https://www.dell.com/support/kbdoc/de-de/000157711/isilon-onefs-how-to-replace-or-renew-the-ssl-certificate-used-for-the-isilon-web-administration-interface

without the creation steps for the certificates.

Thank you.

**Comment by anupamaloke** [comment]
@xschlef, thank you for submitting the feature request. I have added it to the backlog and we will accordingly triage and prioritize it for future releases.

**Comment by anupamaloke** [comment]
Closed via #72
