### ISSUE TITLE
[BUG] Using dellemc.powerscale.info does not return info on all nodes when cluster is version 9.5.0.0

### ISSUE THREAD

**Issue by scottgiff** [dell/ansible-powerscale#52]
I'm using the ansible module dellemc.powerscale.info to retrieve information about cluster nodes.   When the OneFS version is 9.5.0.0 the module does not return info on all nodes, only the node that is the target of the api call.  I've tracked it down to the isi_sdk_9_1_0 pip module requirement.

In that module the get_cluster_nodes api call is using /platform/10/cluster/nodes api path.   This call when executed against a 9.5.0.0 OneFS cluster will only return a single node. Executed against OneFS 9.3.0.0 does retrun all node info as expected.

If I use postman and access any other platform version [3,5,7,12,14,15,16] against 9.5.0.0. I get the full list of node info as expected.

I don't know who is maintaining the pip module isi_sdk_9_1_0, but if there were modules that supported later versions it would be helpful. ( i.e. isi_sdk_9_3_0, isi_sdk_9_4_0...)  OR support the isilon_sdk pip module which contains all sdk version.

**Comment by anupamaloke** [comment]
@scottgiff, as of now, we don't support OneFS 9.5.0.0. It is going to be supported with our next release coming out sometime in Q2.

**Comment by anupamaloke** [comment]
Closed by #56
