### ISSUE TITLE
Unable to import dellemc.powerscale.filesystem due to invalid syntax

### ISSUE THREAD

**Issue by Javedkhansiddiqui** [dell/ansible-powerscale#58]
### Unable to import dellemc.powerscale.filesystem due to invalid syntax

We are running one of ansible-galaxy library(dellemc.powerscale) , which got upgraded to new version recently (probably 20 days ago)post that we can not able to use this module like :- dellemc.powerscale.filesystem , dellemc.powerscale.smb etc.
and got error

![Get filesystem details in System Access Zone without Snapshots](https://github.com/dell/ansible-powerscale/assets/47832136/1e67158c-2093-47fe-bbd2-f51663b2fe9f)

![Unable to import dellemc.powerscale.filesystem due to invalid syntax](https://github.com/dell/ansible-powerscale/assets/47832136/190eb2b5-af7e-44ef-ba9d-c492547dabe9)

**Comment by Jennifer-John** [comment]
Hi @Javedkhansiddiqui 

I tried to install the collection 2.0.0 tar from ansible-galaxy and tried executing the get call using the shared playbook syntax. The execution seems to work fine with the tar file from https://galaxy.ansible.com/dellemc/powerscale

I have tried a get call in both filesystem and smb.
Could you try to re-install the collection and let us know if you are still facing this issue to debug further?

Thanks,
Jennifer.
