### ISSUE TITLE
[FEATURE]: Add support for manually running a preexisting SyncIQ schedule/job

### ISSUE THREAD

**Issue by mikeyd810** [dell/ansible-powerscale#62]
Looking for a task to be added to start a preexisting SyncIQ schedule/job

Work around using a built in command or passing as shell CLI level command right now.

**Comment by anupamaloke** [comment]
@mikeyd810,  thank you for submitting this feature request. We will triage and accordingly prioritize it for future releases.

**Comment by anupamaloke** [comment]
Closed via #67
