### ISSUE TITLE
[FEATURE]: Add support for "run_as_root" for SMB module

### ISSUE THREAD

**Issue by rom357** [dell/ansible-powerscale#63]
While it looks available on the SDK, it seems not possible to create/modify "run_as_root" permissions via Ansible SMB module:

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (dellemc.powerscale.smb) module: **run_as_root** Supported parameters include: access_based_enumeration, access_based_enumeration_root_only, access_zone, allow_variable_expansion, api_password, api_user, auto_create_directory, browsable, ca_timeout, ca_write_integrity, change_notify, continuously_available, create_path, description, directory_create_mask, directory_create_mode, file_create_mask, file_create_mode, file_filter_extension, file_filtering_enabled, host_acls, impersonate_guest, impersonate_user, new_share_name, ntfs_acl_support, onefs_host, oplocks, path, permissions, port_no, share_name, smb3_encryption_enabled, state, strict_ca_lockout, verify_ssl"}`

I couldn't find any workaround.

Thanks.

**Comment by anupamaloke** [comment]
@rom357, this should be available with latest release that is coming out in couple of days.

**Comment by rom357** [comment]
@anupamaloke, Thanks for your feedback.
Do you know when this new version will be published?

**Comment by anupamaloke** [comment]
@rom357 I guess I misspoke. While this feature has been added to the NFS module in v2.2.0 release, it is yet to be implemented for SMB module. This support for SMB module is in our backlog that will be delivered in future release.

**Comment by tenortim** [comment]
I have created code to support this feature and it passes my basic testing (create a share with a "run_as_root" entry, modify it in various ways etc.).
I will submit a PR.
Currently, it just adds the needed code to smb.py and doesn't touch any of the version numbers which I presume will need to be bumped.
I work in the PowerScale engineering org at Dell.

**Comment by anupamaloke** [comment]
Closed via #80
