### ISSUE TITLE
[QUESTION]: Need clarification on dual-licensing

### ISSUE THREAD

**Issue by moriyoshi** [dell/ansible-powerscale#71]
From `README.md`:

> Ansible collection for PowerScale is released and licensed under the GPL-3.0 license. See [LICENSE](https://github.com/dell/ansible-powerscale/blob/2.4.1/LICENSE) for the full terms. Ansible modules and modules utilities that are part of the Ansible collection for PowerScale are released and licensed under the Apache 2.0 license. See [MODULE-LICENSE](https://github.com/dell/ansible-powerscale/blob/2.4.1/MODULE-LICENSE) for the full terms.

Actually the Python scripts under `plugins/modules` are labelled with AL2, but the rest of the repository mostly consists of documents and YAMLs, and to me there seems to be no obvious reasons to publish those under GPLv3. So the one viable possibility would be that the whole content of the project is intended ot be dual-licensed.  How do I have to understand the licensing model?

**Comment by anupamaloke** [comment]
@moriyoshi, the powerscale ansible collection follows the licensing requirement as mentioned in [Collection licensing requirements](https://docs.ansible.com/ansible/latest/community/collection_contributors/collection_requirements.html#id33).

**Comment by anupamaloke** [comment]
@moriyoshi, I am closing this issue. Please feel free to re-open this issue or open a new one if you have any further questions.
