### ISSUE TITLE
[FEATURE]: Add support for check and diff options to module networkpools

### ISSUE THREAD

**Issue by nikolisg7** [dell/ansible-powerscale#75]
**Describe the solution you'd like**
Since network pool configuration is a sensible matter to the effect that even small mistakes or typos could affect basic connectivity to the cluster, it would be very helpful to be able to run tasks for networkpool configuration in ansible check mode with a diff report before real deployment to minimize any risks

**Describe alternatives you've considered**
An alternative would be to read active cluster configuration into a dict and compare values with the ones the ansible tasks WOULD submit, but this is a complex untertaking and hard to implement with ansible code; would be much more straightforward to do in Python at module level. 
It is also considered best practice for modules to support check_mode and diff whenever possible  

Thanks!

**Additional context**
None

**Comment by anupamaloke** [comment]
@nikolisg7, thank you for submitting the feature request. I have added this to the backlog and will accordingly prioritize it for future release.

**Comment by anupamaloke** [comment]
Closed by #94
