### ISSUE TITLE
[BUG]: dellemc.powerscale.info with parameter smb_files is not cluster aware

### ISSUE THREAD

**Issue by eschek87** [dell/ansible-powerscale#77]
If I run
- name: Get list of smb open files of the PowerScale cluster
  dellemc.powerscale.info:
    onefs_host: "{{onefs_host}}"
    verify_ssl: "{{verify_ssl}}"
    api_user: "{{api_user}}"
    api_password: "{{api_password}}"
    gather_subset:
      - smb_files

I get only the smb openfiles for that node which I specify in "onefs_host" and not from the whole cluster.

**Comment by anupamaloke** [comment]
@eschek87, thank you for submitting the feature request. I have added it to the backlog and we will accordingly prioritize it for future releases.

**Comment by haider-bawazir** [comment]
Is this operation even supported by OneFS rest api? 
/protocols/smb/openfiles/ also returna a very limited number of files, no matter how high the limit parameter is set.

**Comment by sachin-apa** [comment]
@eschek87 @haider-bawazir This operation is not supported on direct API calls, we need to loop in all the host under the cluster and get the details of smb.
While we enhance the info module make this changes, please find the attached playbook (please change the extension of file to yml) that gets the smb_files of the cluster assuming that the creds are same.
[smb_file.txt](https://github.com/user-attachments/files/17023707/smb_file.txt)
