### ISSUE TITLE
Ansible support to Create/Delete Access Zones

### ISSUE THREAD

**Issue by dileepbg** [dell/ansible-powerscale#8]
Currently, there is no support in Ansible to create/delete the access zone. Will this be supported in upcoming releases .? If we want to implement this change, Do we need to update the SDK or Shall I get more information on this.

@rajendravarma077 @walker2 @dattaarindam @meshuga

**Comment by rajendraindukuri** [comment]
Hi @dileepbg We are adding support for create access zone in the current release i.e., 1.4.0.

We will discuss about the feasibility of adding delete in upcoming releases based on our priorities. Thanks

**Comment by dileepbg** [comment]
@rajendraindukuri , Thanks for sharing the updates and When Can we expect the new release 1.4.0.

FYI: I found this Repo to create an Access zone using URI module
https://github.com/Isilon/ansible_guide_examples 

Please share if you know any Repo where I can refer sample playbooks related to powerscale configuration

**Comment by anupamaloke** [comment]
@dileepbg, Appreciate if you can share the list of PowerScale configuration use-cases that you are looking to automate?

**Comment by rajendraindukuri** [comment]
@dileepbg Create access zone functionality is available as part of  latest release https://github.com/dell/ansible-powerscale/tree/1.4.0

And let us know what is the specific use case that you are looking for samples. we can provide you the samples and also we provided samples for each module as part of https://github.com/dell/ansible-powerscale/blob/1.4.0/docs/Product%20Guide.md .  Feel free to get back to us if tat does nt help.

**Comment by anupamaloke** [comment]
@dileepbg, I will be closing this issue now that the Create Access Zone support has been added in the latest version 1.4.0. In case you run into any issue with the module or has a new requirement, please feel free to create an issue or reopen this one.

**Comment by dileepbg** [comment]
@anupamaloke @rajendraindukuri thanks for the update. I am using the Create az module with the latest release. Its working fine and I will raise a new ticket for any specific requirement
