### ISSUE TITLE
[FEATURE]: Add missing ADS options for ads module

### ISSUE THREAD

**Issue by nikolisg7** [dell/ansible-powerscale#95]
**Describe the solution you'd like**
The ads module should support all OneFS options for AD management. In my case I was first looking for the option `assume_default_domain`, but apparently it is not included in the current version of the ads module. The same holds for other important options we need to set, e.g. `lookup_users`, `lookup_groups` etc. Thanks!

**Describe alternatives you've considered**
I could append an `uri` task in ansible to manage the settings/options missing from the ads module directly with the OneFS API. But then I wouldn't really need the ads module anymore :- )

**Additional context**
The available options are documented in the API: `https://<onefs_host>:8080/platform/auth/providers/ads?describe`
Thanks!

**Comment by anupamaloke** [comment]
@nikolisg7, thank you for submitting this feature request. This has been added to the backlog and will be prioritized accordingly for future monthly releases.
